import type { Metadata } from "next";
import { ReactLenis } from "@/lib/lenis"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body>
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
